yata_data_retriever_homepage:
    path:     /
    defaults: { _controller: YATADataRetrieverBundle:Twitter:index }

yata_data_retriever_tweet:
    path:     /tweet
    defaults: { _controller: YATADataRetrieverBundle:Twitter:tweet }
